flags: {}
packages:
- '.'
extra-deps:
- Glob-0.7.5
- MemoTrie-0.6.4
- StateVar-1.1.0.3
- abstract-deque-0.3
- abstract-par-0.3.3
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- base-orphans-0.5.3
- bifunctors-5.2.1
- blaze-builder-0.4.0.1
- cassava-0.4.5.0
- cereal-0.5.1.0
- comonad-5
- contravariant-1.4
- cpphs-1.20
- criterion-1.1.1.0
- data-default-class-0.0.1
- dependent-map-0.2.1.0
- dependent-sum-0.3.2.1
- distributive-0.5.0.2
- erf-2.0.0.0
- exception-transformers-0.4.0.3
- haskell-src-exts-1.17.1
- haskell-src-meta-0.6.0.13
- hastache-0.6.1
- ieee754-0.7.8
- math-functions-0.1.5.2
- monad-par-0.3.4.7
- monad-par-extras-0.3.3
- mwc-random-0.13.4.0
- optparse-applicative-0.12.1.0
- parsec-3.1.9
- polyparse-1.11
- profunctors-5.2
- random-1.1
- ref-tf-0.4
- safe-0.3.9
- semigroupoids-5.0.1
- semigroups-0.18.1
- split-0.2.3
- statistics-0.13.2.3
- tagged-0.8.3
- th-expand-syns-0.3.0.6
- th-lift-0.7.6
- th-orphans-0.13.0
- th-reify-many-0.1.4
- these-0.6.2.1
- transformers-compat-0.5.1.4
- vector-algorithms-0.7.0.1
- vector-binary-instances-0.2.1.1
- vector-th-unbox-0.2.1.4
- void-0.7.1
resolver: ghcjs-0.2.0.20151230.3_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
      source:
            ghcjs-0.2.0.20151230.3_ghc-7.10.3:
                    url: "https://github.com/nrolland/ghcjs/releases/download/v.0.2.0.20151230.3/ghcjs-0.2.0.20151230.3.tar.gz"
